Feature/non 82
paulmv34/ReactGameWithSVG pull request #10
Opened 2023-12-13 12:43 UTC by Radik152

### Какую задачу решаем
Страница профиля+изменение автара/пароля+api
Чтобы потестить api, можно войти в аккаунт через https://ya-praktikum.tech/api/v2/swagger/#/Users/put_user_profile и уже потыкать

### Скриншоты/видяшка (если есть)
![Screenshot_1](https://github.com/paulmv34/ReactGameWithSVG/assets/73600239/6152eb42-3062-4249-a857-01087e645d80)

2023-12-13 18:11 UTC, paulmv34 commented
Вроде прицепилось. Да и ветка названа корректно: feature/non-82.
https://disk.yandex.ru/i/XCZxtox34gbh0A

2023-12-13 18:14 UTC, Radik152 commented
> Будет ли синхронизирован гит с linear при таком названии ветки?

А название кстати, копировал из linear

2023-12-13 18:15 UTC, amforzuf approved these changes
Проделана хорошая работа

#### Что особенно хорошо:
- Вынесен BASE_URL
- Создан компонент Title
- Четкое следование согласованной архитектуре проекта

#### Можно лучше:
- В методе onSubmit предполагается выполнение асинхронной операции с задержкой в 3 секунды. Можно обрабатывать ошибки при выполнении операции и уведомлять пользователя о статусе операции.

2023-12-13 20:27 UTC, IvanPeleshok requested changes
Проделана большая работа!
Отлично потрудились!
Чувствуется, что имеется опыт разработки на реакте

Есь замечания, предлагаю доработать

Оставил комментарии по улучшению реализации фичи

Хорошего дня :)

2023-12-13 20:27 UTC, IvanPeleshok commented on packages/client/src/api/userApi.ts
> +  changeUserProfileData(data: TUserData) {
Не увидел, чтобы вы обрабатывали ответ промиса

Если он вернется с reject, то исключение будет выброшено наружу
Предлагаю обработать данный кейс с помощью try / catch

2023-12-13 20:27 UTC, IvanPeleshok commented on packages/client/src/pages/ChangePassword/components/ChangePasswordForm/ChangePasswordForm.tsx
> +      console.log(values)
Насколько нужна отладка в деве?

2023-12-13 20:27 UTC, IvanPeleshok commented on packages/client/src/pages/ChangePassword/components/ChangePasswordForm/ChangePasswordForm.tsx
> +        <Button variant="contained" fullWidth className={styles.button} type="submit" disabled={formik.isSubmitting}>
Если везде переносите пропсы, то лучше придерживаться такого формата

2023-12-13 20:27 UTC, IvanPeleshok commented on packages/client/src/pages/Profile/components/ProfileInfo/ProfileInfo.module.scss
> +
Лишнее отступы

2023-12-13 20:27 UTC, IvanPeleshok commented on packages/client/src/pages/Profile/components/ProfileInfo/ProfileInfo.tsx
> +const ProfileInfo: FC = () => {
Аналогичные вопросы-замечания

2023-12-13 20:27 UTC, IvanPeleshok commented on packages/client/src/pages/Profile/components/ProfileInfo/types.ts
> +  // avatar?: string | null
Если не используется, то лучше убрать

2023-12-14 21:13 UTC, IvanPeleshok approved these changes
Всё здорово, апрув!
Хорошего дня :)

2023-12-15 04:20 UTC, merged