Feature/non 57
paulmv34/ReactGameWithSVG pull request #29
Opened 2024-01-25 15:45 UTC by Dastan64

### Какую задачу решаем

Подключено API лидерборда, рекорд пользователя записывается в таблицу по окончании игры, также пользователь может посмотреть таблицу лидеров

**Remark:** _API работает не совсем понятным образом (обсуждалось в треде в Пачке), но можно проверить отправку запросов и получение данных по команде._

2024-01-26 04:39 UTC, ZaoBaoo commented
По коду вроде все ок. Сейчас проект запущу, потестирую

2024-01-26 09:15 UTC, Dastan64 commented
@paulmv34, _где data - любые данные по игре, а ratingFieldName - поле для сравнения результата игры. Если прислать значение меньше, чем предыдущее, ничего не произойдет, а если большее - данные перезапишутся._

Т.к. я указываю `score` как `ratingFieldName`, то по сути для API должна сохранить только запись с наибольшим `score`.

Если я правильно тебя понял.

2024-01-26 14:11 UTC, ZaoBaoo approved these changes
Набил очков на первом уровне и умер - результат корректно отобразился. Потом прошел до 4 уровня и умер - результат обновился. Хорошая работа, Дастан 👍🏾
![image](https://github.com/paulmv34/ReactGameWithSVG/assets/86558294/c0603c53-8184-4ffb-8d72-a2f70a015222)

2024-01-27 14:25 UTC, Olegas requested changes
Добрый день. 
Есть замечания по коду.
Написал подробные комментарии что и где не так.
Давай доработаем

2024-01-27 14:25 UTC, Olegas commented on packages/client/src/mechanics/services/Game/Game.ts
> +        ratingFieldName: RATING_FIELD_NAME,
Вот эти данные о имени команды и поле с рейтингм лучше убрать в API т.к. они одинаковые для всего приложения. А передавать только сам рейтинг и пользователя. Кстати, дату тоже можно убрать в API ведь всегда передается текущая.

2024-01-27 14:25 UTC, Olegas commented on packages/client/src/mechanics/services/Game/Game.ts
> +          nickname: store.getState().user.user?.display_name || 'Fancy Unicorn',
Вот так лучше не делать. Потому что теперь логика игры (которая по идее должна быть абстрагирована от всего приложения максимально) знает что есть какой-то redux, какой-то стор и как в нем что расположено. Лучше из игры выставить колбэк, где будет уровень и набранные очки. А само приложение на него отреагирует и отправит данные в бэкэнд. Т.к. приложение будет связующим узлом.

2024-01-27 14:25 UTC, Olegas commented on packages/client/src/modules/LeaderTable/LeaderTable.tsx
> +        {records.length > 0 && records.map(({ data: record }) => <Row record={record} key={uuidv4()} />)}
Случайные ключи - это плохо. Каждый раз будет перерендер. Надо взять что-то из записи рекорда. Можно составной ключ какой-то сделать например игрок + дата

2024-01-27 14:25 UTC, Olegas commented on packages/client/src/modules/LeaderTable/components/Row/Row.tsx
> +  const adaptedDate = date ? new Date(date).toLocaleDateString() : 'N/A'
Рассмотрите вариант трансформировать дату в момент получения данных вместо того что бы на каждый рендер каждой строки делать операцию конвертации

2024-01-27 16:48 UTC, Olegas commented on packages/client/src/pages/Game/Game.tsx
> +  const game = Tanchiki.create(onUpdateLeaderboard)
Обратите внимание, тут есть не очень удачное решение. Это не блокирует приемку.

Каждый рендер компонента Game вызывается метод Tanchiki.create. Сейчас это не мешает, потому что там singleton но вообще это не очень правильно. Это могло бы выглядеть примерно как-то так (покажу общую идею)

```javascript
useEffect(() => {
   function onUpdateLeaderboard() { ... }
   const game=Tanchiki.create(onUpdateLeaderboard)
}, [])
```

2024-01-27 16:48 UTC, Olegas approved these changes
Работа принята

2024-01-27 16:59 UTC, merged