Feature/non 61
paulmv34/ReactGameWithSVG pull request #37
Opened 2024-02-10 11:47 UTC by amforzuf

### Какую задачу решаем
https://linear.app/no-handlebars/issue/NON-61/realizovat-api-dlya-foruma

2024-02-10 14:06 UTC, paulmv34 approved these changes
Отличная работа!

Хорошая структура папок. 
Разработаны необходимые модели с использованием Sequelize и контроллеры.
Отлично, что проверяется авторизация пользователя.

2024-02-10 15:43 UTC, Dastan64 approved these changes
Хорошая работа. Лайк за разделение на утилки и отдельные модули!

2024-02-10 17:12 UTC, Olegas requested changes
Добрый день.
Все хорошо сделано, есть мидлвара для авторизации, данный пользователя кэшируются, есть проверка прав на операции.
Есть недостаток - отсутствуют индексы для поиска связанных сущностей. Написал комментарии чего и где не хватает.
Давай доработаем.

2024-02-10 17:12 UTC, Olegas commented on packages/server/models/ForumMessage.ts
> +export class ForumMessage extends Model {
Для поиска сообщения форума по топику нужен индекс (по полю topic_id)

2024-02-10 17:12 UTC, Olegas commented on packages/server/models/ForumTopic.ts
> +export class ForumTopic extends Model {
Нужен индекс по section_id

2024-02-11 09:45 UTC, Olegas approved these changes
Работа принята

2024-02-11 10:17 UTC, merged